#!/bin/bash
# Local Agent Runner
# Picks up GitHub issues labeled 'auto' or 'auto-merge', solves them one by one.
# - 'auto' label: opens PR, waits for your review before merging
# - 'auto-merge' label: opens PR and merges immediately (no review)
#
# Usage: bash scripts/agent.sh

export PATH="/c/Program Files/GitHub CLI:$PATH"

echo "=== Motion Local Agent ==="
echo "Watching for issues labeled 'auto' or 'auto-merge'..."
echo ""

while true; do
  # Ensure we're on main and up to date
  git checkout main --quiet 2>/dev/null || true
  git pull origin main --quiet 2>/dev/null || true

  # Get next open issue (check auto-merge first, then auto)
  ISSUE_NUM=$(gh issue list --label auto-merge --state open --limit 1 --json number --jq '.[0].number')
  LABEL="auto-merge"

  if [ -z "$ISSUE_NUM" ] || [ "$ISSUE_NUM" = "null" ]; then
    ISSUE_NUM=$(gh issue list --label auto --state open --limit 1 --json number --jq '.[0].number')
    LABEL="auto"
  fi

  if [ -z "$ISSUE_NUM" ] || [ "$ISSUE_NUM" = "null" ]; then
    echo "No issues found. Polling again in 30s... (Ctrl+C to stop)"
    sleep 30
    continue
  fi

  ISSUE_TITLE=$(gh issue view "$ISSUE_NUM" --json title --jq '.title')
  ISSUE_BODY=$(gh issue view "$ISSUE_NUM" --json body --jq '.body')

  echo "----------------------------------------"
  echo "[$LABEL] Issue #$ISSUE_NUM: $ISSUE_TITLE"
  echo "----------------------------------------"

  # Create a branch
  BRANCH="auto/issue-$ISSUE_NUM"
  git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

  # Write prompt to file to avoid shell escaping issues
  cat > .agent-prompt.txt << PROMPT_EOF
You are working on the repo 'KeshavM05/Lotion'.

GitHub Issue #$ISSUE_NUM: $ISSUE_TITLE

Description:
$ISSUE_BODY

Instructions:
1. Read CLAUDE.md for project conventions
2. Explore the relevant parts of the codebase
3. Implement the fix/feature described in the issue
4. Run 'npm run build' to verify no TypeScript errors
5. Commit your changes with a descriptive message

Keep changes minimal and focused. Do not modify unrelated files.
PROMPT_EOF

  # Run Claude Code
  claude --dangerously-skip-permissions -p "$(cat .agent-prompt.txt)"

  # Clean up prompt file
  rm -f .agent-prompt.txt

  # Push branch and create PR
  git push origin "$BRANCH" --force-with-lease
  PR_URL=$(gh pr create \
    --title "fix: resolve #$ISSUE_NUM - $ISSUE_TITLE" \
    --body "Automated fix for #$ISSUE_NUM

Closes #$ISSUE_NUM

---
Generated by local Claude Code agent" \
    --base main \
    --head "$BRANCH" 2>/dev/null || echo "already exists")

  echo ""
  echo "PR ready: $PR_URL"

  if [ "$LABEL" = "auto-merge" ]; then
    # Auto-merge: no review needed
    echo "Auto-merge label detected. Merging immediately..."
    gh pr merge "$BRANCH" --squash --delete-branch
    echo "Merged!"
    git checkout main --quiet
    git pull origin main --quiet
  else
    # Review mode: wait for user
    echo ""
    echo "Review the changes, then:"
    echo "  - Press ENTER to merge and continue to next issue"
    echo "  - Type 'skip' to skip this issue and move on"
    echo "  - Type 'quit' to stop the agent"
    echo ""
    read -r ACTION

    case "$ACTION" in
      skip)
        echo "Skipping #$ISSUE_NUM..."
        git checkout main --quiet
        git branch -D "$BRANCH" 2>/dev/null
        ;;
      quit)
        echo "Stopping agent."
        git checkout main --quiet
        exit 0
        ;;
      *)
        # Merge the PR
        gh pr merge "$BRANCH" --squash --delete-branch
        echo "Merged! Moving to next issue..."
        git checkout main --quiet
        git pull origin main --quiet
        ;;
    esac
  fi

  echo ""
done

echo "Agent stopped."
